server :
  port : 9494
spring :
  data :
    mongodb :
      uri: mongodb+srv://kmsaleh:1234@cluster0.yuxq7dc.mongodb.net/myDB?retryWrites=true&w=majority
  profiles:
    active:
     - User-MongoDB
#     - User-JPA
  datasource :
    url : jdbc:h2:mem:testUser
    username : sa
    password : 1234
  h2 :
    console :
      enabled : true
  application :
    name : rds-db